# Generated by Django 4.0.4 on 2022-07-03 21:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('announce', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnnounceOther',
            fields=[
                ('title', models.CharField(max_length=128)),
                ('description', models.TextField()),
                ('price', models.IntegerField()),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='post/thumbnail')),
                ('published', models.BooleanField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='announce.category')),
                ('locality', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='announce.locality')),
                ('notation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='announce.announcenotation')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='imageannounceanimal',
            name='images',
            field=models.ImageField(upload_to='announce/announce_animal'),
        ),
        migrations.AlterField(
            model_name='imageannouncebeautywellness',
            name='images',
            field=models.ImageField(upload_to='announce/announce_beauty_wellness'),
        ),
        migrations.AlterField(
            model_name='imageannouncecar',
            name='images',
            field=models.ImageField(upload_to='announce/announce_car'),
        ),
        migrations.AlterField(
            model_name='imageannounceelectronic',
            name='images',
            field=models.ImageField(upload_to='announce/announce_electronic'),
        ),
        migrations.AlterField(
            model_name='imageannounceemploy',
            name='images',
            field=models.ImageField(upload_to='announce/announce_employ'),
        ),
        migrations.AlterField(
            model_name='imageannounceevent',
            name='images',
            field=models.ImageField(upload_to='announce/announce_event'),
        ),
        migrations.AlterField(
            model_name='imageannouncefashionclothes',
            name='images',
            field=models.ImageField(upload_to='announce/announce_fashion_clothes'),
        ),
        migrations.AlterField(
            model_name='imageannounceformation',
            name='images',
            field=models.ImageField(upload_to='announce/announce_formation'),
        ),
        migrations.AlterField(
            model_name='imageannouncefurnitureappliance',
            name='images',
            field=models.ImageField(upload_to='announce/announce_furniture_appliance'),
        ),
        migrations.AlterField(
            model_name='imageannouncephonetablet',
            name='images',
            field=models.ImageField(upload_to='announce/announce_phone_tablet'),
        ),
        migrations.AlterField(
            model_name='imageannounceservicedelivery',
            name='images',
            field=models.ImageField(upload_to='announce/announce_service_delivery'),
        ),
        migrations.CreateModel(
            name='ImageAnnounceOther',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('images', models.ImageField(upload_to='announce/announce_other')),
                ('announce_other', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='announce.announceother')),
            ],
        ),
    ]
